
```{r message = FALSE}
#Library
library(bnlearn)
library(tidyverse)
library(magrittr)
library(readr)
library(readxl)
```

```{r}
#Creating DAG Graph template
dag <- empty.graph(nodes = c("Age","Sex","Marriage","HType","Income","Npax","Race","PlanningArea","AgeSpouse","RaceSpouse","SexSpouse"))
arc.set <- matrix(c("Age", "Sex",
                    "Age", "Marriage",
                    "Age", "Race",
                    "Age", "Npax",
                    "Sex", "Race",
                    "Sex", "Marriage",
                    "Npax", "HType",
                    "Race", "HType",
                    "HType","PlanningArea",
                    "Age","AgeSpouse",
                    "Marriage","AgeSpouse",
                    "AgeSpouse","RaceSpouse",
                    "Race","RaceSpouse",
                    "Sex","SexSpouse",
                    "Marriage","SexSpouse",
                    "Npax","Income"),
                  byrow = TRUE, ncol = 2,
                  dimnames = list(NULL, c("from", "to")))
arcs(dag) <- arc.set
nodes(dag)
plot(dag)
```
```{r}
#Define Variables
Age.lv <- c("Below 30","30 - 34","35 - 39","40 - 44","45 - 49","50 - 54","55 - 59","60 - 64","65 - 69","70 - 74","75 & Over")
Sex.lv <- c("M", "F")
Marriage.lv <- c("Single","Married","Widowed","Divorced/Separated")
Race.lv <-c("Chinese","Malay","Indian","Others")
HType.lv <- c( "1- And 2-Room Flats 2"," 3-Room Flats","4-Room Flats","5-Room And Executive Flats","Condo- Miniums And Other Apartments","Landed Properties","Others")
Npax.lv<-c("1 Person","2 Person","3 Person","4 Person","5 Person","6 or more")
Income.lv <- c("No working person","Below 1,000","1,000 - 1,499","1,500 - 1,999","2,000 - 2,499","2,500 - 2,999","3,000 - 3,499","3,500 - 3,999","4,000 - 4,499","4,500 - 4,999","5,000 - 5,999","6,000 - 6,999","7,000 - 7,999","8,000 - 8,999","9,000 - 9,999","10,000 - 10,999","11,000 - 11,999","12,000 - 12,999","13,000 - 13,999","14,000 - 14,999","15,000 - 17,499","17,500 - 19,999","20,000 & Over")
AgeSpouse.lv <- c("None","Below 30","30 - 34","35 - 39","40 - 44","45 - 49","50 - 54","55 - 59","60 - 64","65 & Over")
RaceSpouse.lv <- c("None","Chinese","Malay","Indian","Others")
PlanningArea.lv <- c("AngMoKio","Bedok","Bishan","BukitBatok","BukitMerah","BukitPanjang","BukitTimah","ChoaChuKang","Clementi","Geylang","Hougang","JurongEast","JurongWest","Kallang","MarineParade","Novena","Outram","PasirRis","Punggol","Queenstown","Sembawang","Sengkang","Serangoon","Tampines","Tanglin","ToaPayoh","Woodlands","Yishun","Others")
SexSpouse.lv <- c("None","M","F")
```
```{r message=FALSE}
#Copy and paste each respective txt file into its array
age_ar <- read_excel("Inputs/Data_Age.xlsx",col_names = FALSE)
age_ar <- as.numeric(unlist(age_ar))
sex_ar <- read_excel("Inputs/Data_Sex_Age.xlsx",col_names = FALSE)
sex_ar <- as.numeric(unlist(sex_ar))
marriage_ar <- read_excel("Inputs/Data_Marriage_Age_sex.xlsx",col_names = FALSE)
marriage_ar <- as.numeric(unlist(marriage_ar))
HType_ar <- read_excel("Inputs/Data_Htype_Npax_race.xlsx",col_names = FALSE)
HType_ar <- as.numeric(unlist(HType_ar))
Race_ar <- read_excel("Inputs/Data_Race_Age_sex.xlsx",col_names = FALSE)
Race_ar <- as.numeric(unlist(Race_ar))
Npax_ar <- read_excel("Inputs/Data_npax_age.xlsx",col_names = FALSE)
Npax_ar <- as.numeric(unlist(Npax_ar))
Income_ar <- read_excel("Inputs/Data_income_npax.xlsx",col_names = FALSE)
Income_ar <- as.numeric(unlist(Income_ar))
PlanningArea_ar <- read_excel("Inputs/Data_PlanningArea_HType.xlsx",col_names = FALSE)
PlanningArea_ar <- as.numeric(unlist(PlanningArea_ar))
AgeSpouse_ar <- read_excel("Inputs/Data_AgeSpouse_Age_Marriage.xlsx",col_names = FALSE)
AgeSpouse_ar <- as.numeric(unlist(AgeSpouse_ar))
RaceSpouse_ar <- read_excel("Inputs/Data_RaceSpouse_AgeSpouse_Race.xlsx",col_names = FALSE)
RaceSpouse_ar <- as.numeric(unlist(RaceSpouse_ar))
SexSpouse_ar <- read_excel("Inputs/Data_SexSpouse_Sex_Marriage.xlsx",col_names = FALSE)
SexSpouse_ar <- as.numeric(unlist(SexSpouse_ar))
```
```{r}
#Create conditional probability table
Age.prob <- array(age_ar, dim = 11, dimnames = list(Age = Age.lv))
Sex.prob <- array(sex_ar, dim = c(2,11), dimnames = list(Sex = Sex.lv,Age = Age.lv))
Marriage.prob <- array(marriage_ar, dim = c(4,11,2), dimnames = list(Marriage = Marriage.lv, Age = Age.lv, Sex = Sex.lv))
HType.prob <- array(HType_ar, dim = c(7,6,4), dimnames = list(HType = HType.lv, Npax = Npax.lv, Race = Race.lv))
Npax.prob <- array(Npax_ar, dim = c(6,11), dimnames = list(Npax = Npax.lv,Age = Age.lv))
Race.prob <- array(Race_ar, dim = c(4,11,2), dimnames = list(Race = Race.lv,Age = Age.lv, Sex = Sex.lv))
Income.prob <- array(Income_ar, dim = c(23,6), dimnames = list(Income = Income.lv,Npax = Npax.lv))
PlanningArea.prob <- array(PlanningArea_ar, dim = c(29,7), dimnames = list(PlanningArea = PlanningArea.lv,HType= HType.lv))
AgeSpouse.prob <- array(AgeSpouse_ar, dim = c(10,11,4), dimnames = list(AgeSpouse = AgeSpouse.lv,Age= Age.lv,Marriage=Marriage.lv))
RaceSpouse.prob <- array(RaceSpouse_ar, dim = c(5,10,4), dimnames = list(RaceSpouse = RaceSpouse.lv,AgeSpouse= AgeSpouse.lv,Race=Race.lv))
SexSpouse.prob <- array(SexSpouse_ar, dim = c(3,2,4), dimnames = list(SexSpouse = SexSpouse.lv,Sex = Sex.lv,Marriage=Marriage.lv))
cpt <- list(Age = Age.prob, Sex = Sex.prob, Marriage = Marriage.prob, HType = HType.prob,Race = Race.prob,Npax = Npax.prob,Income = Income.prob,PlanningArea = PlanningArea.prob,AgeSpouse = AgeSpouse.prob,RaceSpouse = RaceSpouse.prob,SexSpouse = SexSpouse.prob)
```
```{r}
#Create Bayesian network by fitting DAG with CPT
bn <- custom.fit(dag,cpt)
```
```{r}
set.seed(4231)
#Generate sample 
total= 2000000 #number of household in aggreagated data
sim <- rbn(bn,n=total)
head(sim)
```
```{r}
#convert to Npax to integer
household <- sim %>% mutate(Npax_r = case_when(Npax=="1 Person" ~ 1, Npax =="2 Person" ~ 2, Npax =="3 Person" ~3, Npax =="4 Person" ~ 4, Npax == "5 Person" ~ 5, Npax == "6 or more" ~ 6))
#Change all to factor and add HouseID
household$AgeSpouse <- factor(household$AgeSpouse)
household %<>% mutate(HID = row_number())

#Add randomnized age for spouse
tempage <- as.character(household$AgeSpouse)
tempage <- gsub("None",0,tempage)
tempage <- gsub("Below 30",sample(18:29,1),tempage)
tempage <- gsub("30 - 34",sample(30:34,1),tempage)
tempage <- gsub("35 - 39",sample(35:39,1),tempage)
tempage <- gsub("40 - 44",sample(40:44,1),tempage)
tempage <- gsub("45 - 49",sample(45:49,1),tempage)
tempage <- gsub("50 - 54",sample(50:54,1),tempage)
tempage <- gsub("55 - 59",sample(55:59,1),tempage)
tempage <- gsub("60 - 64",sample(60:64,1),tempage)
tempage <- gsub("65 & Over",sample(65:90,1),tempage)
household %<>% mutate(spouseAge = as.numeric(tempage))
rm(tempage)

#remove unncessary variables
rm(list=setdiff(ls(),c("household","person")))
```